# Generated by Django 3.0.1 on 2020-01-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='img',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
